const modelList = [
  "blackboxai",
  "gpt-4.1-mini",
  "gpt-4.1-nano",
  "gpt-4",
  "gpt-4o",
  "gpt-4o-mini",

  // Trending agent modes
  "Python Agent",
  "HTML Agent",
  "Builder Agent",
  "Java Agent",
  "JavaScript Agent",
  "React Agent",
  "Android Agent",
  "Flutter Agent",
  "Next.js Agent",
  "AngularJS Agent",
  "Swift Agent",
  "MongoDB Agent",
  "PyTorch Agent",
  "Xcode Agent",
  "Azure Agent",
  "Bitbucket Agent",
  "DigitalOcean Agent",
  "Docker Agent",
  "Electron Agent",
  "Erlang Agent",
  "FastAPI Agent",
  "Firebase Agent",
  "Flask Agent",
  "Git Agent",
  "Gitlab Agent",
  "Go Agent",
  "Godot Agent",
  "Google Cloud Agent",
  "Heroku Agent",
]
const trendingAgentMode = {
  "Python Agent": { mode: true, id: "python" },
  "HTML Agent": { mode: true, id: "html" },
  "Builder Agent": { mode: true, id: "builder" },
  "Java Agent": { mode: true, id: "java" },
  "JavaScript Agent": { mode: true, id: "javascript" },
  "React Agent": { mode: true, id: "react" },
  "Android Agent": { mode: true, id: "android" },
  "Flutter Agent": { mode: true, id: "flutter" },
  "Next.js Agent": { mode: true, id: "next.js" },
  "AngularJS Agent": { mode: true, id: "angularjs" },
  "Swift Agent": { mode: true, id: "swift" },
  "MongoDB Agent": { mode: true, id: "mongodb" },
  "PyTorch Agent": { mode: true, id: "pytorch" },
  "Xcode Agent": { mode: true, id: "xcode" },
  "Azure Agent": { mode: true, id: "azure" },
  "Bitbucket Agent": { mode: true, id: "bitbucket" },
  "DigitalOcean Agent": { mode: true, id: "digitalocean" },
  "Docker Agent": { mode: true, id: "docker" },
  "Electron Agent": { mode: true, id: "electron" },
  "Erlang Agent": { mode: true, id: "erlang" },
  "FastAPI Agent": { mode: true, id: "fastapi" },
  "Firebase Agent": { mode: true, id: "firebase" },
  "Flask Agent": { mode: true, id: "flask" },
  "Git Agent": { mode: true, id: "git" },
  "Gitlab Agent": { mode: true, id: "gitlab" },
  "Go Agent": { mode: true, id: "go" },
  "Godot Agent": { mode: true, id: "godot" },
  "Google Cloud Agent": { mode: true, id: "googlecloud" },
  "Heroku Agent": { mode: true, id: "heroku" },
}
export default modelList
export { trendingAgentMode }
