const modelListOrig = [
  "blackboxai",
  "gpt-4.1-mini",
  "gpt-4.1-nano",
  "gpt-4",
  "gpt-4.1",
  "o1",
  "o1-mini",
  "gpt-4o",
  "gpt-4o-mini",
  // Agent Mode
  "Command",
  "Command R",
  "Command R7B 12 2024",
  "Command R Plus 04 2024",
  "Command R Plus",
  "Command A",
  "Command R 08 2024",
  "Command R Plus 08 2024",
  "Command R 03 2024",

  "Mistral-Small",
  "Mistral-7b-Instruct-v0.2",
  "Ministral-8b",
  "Mixtral-8x7b-Instruct",
  "Magistral-Medium-2506-Thinking",
  "Mixtral-8x22b-Instruct",
  "Devstral-Small-Free",
  "Mistral-Large",
  "Mistral-7b-Instruct-Free",
  "Pixtral-12b",
  "Mistral-Saba",
  "Mistral-Tiny",
  "Mistral-Large-2407",
  "Mistral-7b-Instruct-v0.3",
  "Mistral-Small-24b-Instruct-2501-Free",
  "Mistral-Small-3.2-24b-Instruct-Free",
  "Mistral-Small-24b-Instruct-2501",
  "Mistral-7b-Instruct",
  "Mistral-Small-3.2-24b-Instruct",
  "Mistral-Nemo-Free",
  "Mistral-7b-Instruct-v0.1",
  "Devstral-Small",
  "Ministral-3b",
  "Pixtral-Large-2411",
  "Mistral-Small-3.1-24b-Instruct-Free",
  "Magistral-Medium-2506",
  "Mistral-Medium-3",
  "Codestral-2501",
  "Cognitivecomputations-Dolphin3.0-Mistral-24b-Free",
  "Magistral-Small-2506",
  "Cognitivecomputations-Dolphin3.0-r1-Mistral-24b-Free",
  "Mistral-Large-2411",
  "Mistral-Nemo",
  "Mistral-Small-3.1-24b-Instruct",

  "Claude-3-Haiku:beta",
  "Claude-3.7-Sonnet",
  "Claude-3.5-Haiku",
  "Claude-3.5-Haiku:beta",
  "Claude-3.5-Haiku-20241022:beta",
  "Claude-Opus-4",
  "Claude-3-Sonnet",
  "Claude-3.5-Haiku-20241022",
  "Claude-2.1",
  "Claude-3-Haiku",
  "Claude-3.5-Haiku:beta",
  "Claude-3.7-Sonnet:thinking",
  "Claude-3-Opus",
  "Claude-2.0",
  "Claude-3.5-Sonnet-20240620:beta",
  "Claude-3.5-Sonnet",
  "Claude-2.0:beta",
  "Claude-3.7-Sonnet:beta",
  "Claude-2",
  "Claude-Sonnet-4",
  "Claude-3-Opus:beta",
  "Claude-2.1:beta",
  "Claude-3-Sonnet:beta",
  "Claude-3.5-Sonnet-20240620",
  "Claude-2:beta",
  "Gemini-2.5-Flash-Preview-05-20",
  "Gemini-2.5-Flash-Preview-05-20:Thinking",
  "Gemini-2.5-Pro-Preview-05-06",
  "Gemini-2.5-Flash-Lite-Preview-06-17",
  "Gemini-2.5-Flash-Preview",
  "Gemini-Pro-1.5",
  "Gemini-2.5-Pro-Exp-03-25",
  "Gemini-2.5-Flash",
  "Gemini-2.0-Flash-Exp:Free",
  "Gemini-Flash-1.5",
  "Gemini-2.5-Pro",
  "Gemini-2.5-Pro-Preview",
  "Gemini-Flash-1.5-8b",
  "Gemini-2.0-Flash-Lite-001",
  "Gemini-2.0-Flash-001",
  "Gemini-2.5-Flash-Preview:Thinking",
  // Trending agent modes
  "Python Agent",
  "HTML Agent",
  "Builder Agent",
  "Java Agent",
  "JavaScript Agent",
  "React Agent",
  "Android Agent",
  "Flutter Agent",
  "Next.js Agent",
  "AngularJS Agent",
  "Swift Agent",
  "MongoDB Agent",
  "PyTorch Agent",
  "Xcode Agent",
  "Azure Agent",
  "Bitbucket Agent",
  "DigitalOcean Agent",
  "Docker Agent",
  "Electron Agent",
  "Erlang Agent",
  "FastAPI Agent",
  "Firebase Agent",
  "Flask Agent",
  "Git Agent",
  "Gitlab Agent",
  "Go Agent",
  "Godot Agent",
  "Google Cloud Agent",
  "Heroku Agent",
]
const trendingAgentMode = {
  "Python Agent": { mode: true, id: "python" },
  "HTML Agent": { mode: true, id: "html" },
  "Builder Agent": { mode: true, id: "builder" },
  "Java Agent": { mode: true, id: "java" },
  "JavaScript Agent": { mode: true, id: "javascript" },
  "React Agent": { mode: true, id: "react" },
  "Android Agent": { mode: true, id: "android" },
  "Flutter Agent": { mode: true, id: "flutter" },
  "Next.js Agent": { mode: true, id: "next.js" },
  "AngularJS Agent": { mode: true, id: "angularjs" },
  "Swift Agent": { mode: true, id: "swift" },
  "MongoDB Agent": { mode: true, id: "mongodb" },
  "PyTorch Agent": { mode: true, id: "pytorch" },
  "Xcode Agent": { mode: true, id: "xcode" },
  "Azure Agent": { mode: true, id: "azure" },
  "Bitbucket Agent": { mode: true, id: "bitbucket" },
  "DigitalOcean Agent": { mode: true, id: "digitalocean" },
  "Docker Agent": { mode: true, id: "docker" },
  "Electron Agent": { mode: true, id: "electron" },
  "Erlang Agent": { mode: true, id: "erlang" },
  "FastAPI Agent": { mode: true, id: "fastapi" },
  "Firebase Agent": { mode: true, id: "firebase" },
  "Flask Agent": { mode: true, id: "flask" },
  "Git Agent": { mode: true, id: "git" },
  "Gitlab Agent": { mode: true, id: "gitlab" },
  "Go Agent": { mode: true, id: "go" },
  "Godot Agent": { mode: true, id: "godot" },
  "Google Cloud Agent": { mode: true, id: "googlecloud" },
  "Heroku Agent": { mode: true, id: "heroku" },

  "Claude-3-Haiku:beta": {
    mode: true,
    name: "anthropic/claude-3-haiku:beta",
    id: "Claude-3-Haiku:beta",
  },
  "Claude-3.7-Sonnet": {
    mode: true,
    name: "anthropic/claude-3.7-sonnet",
    id: "Claude-3.7-Sonnet",
  },
  "Claude-3.5-Haiku": {
    mode: true,
    name: "anthropic/claude-3.5-haiku",
    id: "Claude-3.5-Haiku",
  },
  "Claude-3.5-Haiku:beta": {
    mode: true,
    name: "anthropic/claude-3.5-haiku:beta",
    id: "Claude-3.5-Haiku:beta",
  },
  "Claude-3.5-Haiku-20241022:beta": {
    mode: true,
    name: "anthropic/claude-3.5-haiku-20241022:beta",
    id: "Claude-3.5-Haiku-20241022:beta",
  },
  "Claude-Opus-4": {
    mode: true,
    name: "anthropic/claude-opus-4",
    id: "Claude-Opus-4",
  },
  "Claude-3-Sonnet": {
    mode: true,
    name: "anthropic/claude-3-sonnet",
    id: "Claude-3-Sonnet",
  },
  "Claude-3.5-Haiku-20241022": {
    mode: true,
    name: "anthropic/claude-3.5-haiku-20241022",
    id: "Claude-3.5-Haiku-20241022",
  },
  "Claude-2.1": { mode: true, name: "anthropic/claude-2.1", id: "Claude-2.1" },
  "Claude-3-Haiku": {
    mode: true,
    name: "anthropic/claude-3-haiku",
    id: "Claude-3-Haiku",
  },
  "Claude-3.5-Haiku:betax": {
    mode: true,
    name: "anthropic/claude-3.5-haiku:beta",
    id: "Claude-3.5-Haiku:beta",
  },
  "Claude-3.7-Sonnet:thinking": {
    mode: true,
    name: "anthropic/claude-3.7-sonnet:thinking",
    id: "Claude-3.7-Sonnet:thinking",
  },
  "Claude-3-Opus": {
    mode: true,
    name: "anthropic/claude-3-opus",
    id: "Claude-3-Opus",
  },
  "Claude-2.0": { mode: true, name: "anthropic/claude-2.0", id: "Claude-2.0" },
  "Claude-3.5-Sonnet-20240620:beta": {
    mode: true,
    name: "anthropic/claude-3.5-sonnet-20240620:beta",
    id: "Claude-3.5-Sonnet-20240620:beta",
  },
  "Claude-3.5-Sonnet": {
    mode: true,
    name: "anthropic/claude-3.5-sonnet",
    id: "Claude-3.5-Sonnet",
  },
  "Claude-2.0:beta": {
    mode: true,
    name: "anthropic/claude-2.0:beta",
    id: "Claude-2.0:beta",
  },
  "Claude-3.7-Sonnet:beta": {
    mode: true,
    name: "anthropic/claude-3.7-sonnet:beta",
    id: "Claude-3.7-Sonnet:beta",
  },
  "Claude-2": { mode: true, name: "anthropic/claude-2", id: "Claude-2" },
  "Claude-Sonnet-4": {
    mode: true,
    name: "anthropic/claude-sonnet-4",
    id: "Claude-Sonnet-4",
  },
  "Claude-3-Opus:beta": {
    mode: true,
    name: "anthropic/claude-3-opus:beta",
    id: "Claude-3-Opus:beta",
  },
  "Claude-2.1:beta": {
    mode: true,
    name: "anthropic/claude-2.1:beta",
    id: "Claude-2.1:beta",
  },
  "Claude-3-Sonnet:beta": {
    mode: true,
    name: "anthropic/claude-3-sonnet:beta",
    id: "Claude-3-Sonnet:beta",
  },
  "Claude-3.5-Sonnet-20240620": {
    mode: true,
    name: "anthropic/claude-3.5-sonnet-20240620",
    id: "Claude-3.5-Sonnet-20240620",
  },
  "Claude-2:beta": {
    mode: true,
    name: "anthropic/claude-2:beta",
    id: "Claude-2:beta",
  },
  "Mistral-Small": {
    mode: true,
    name: "mistralai/mistral-small",
    id: "Mistral-Small",
  },
  "Mistral-7b-Instruct-v0.2": {
    mode: true,
    name: "mistralai/mistral-7b-instruct-v0.2",
    id: "Mistral-7b-Instruct-v0.2",
  },
  "Ministral-8b": {
    mode: true,
    name: "mistralai/ministral-8b",
    id: "Ministral-8b",
  },
  "Mixtral-8x7b-Instruct": {
    mode: true,
    name: "mistralai/mixtral-8x7b-instruct",
    id: "Mixtral-8x7b-Instruct",
  },
  "Magistral-Medium-2506-Thinking": {
    mode: true,
    name: "mistralai/magistral-medium-2506:thinking",
    id: "Magistral-Medium-2506-Thinking",
  },
  "Mixtral-8x22b-Instruct": {
    mode: true,
    name: "mistralai/mixtral-8x22b-instruct",
    id: "Mixtral-8x22b-Instruct",
  },
  "Devstral-Small-Free": {
    mode: true,
    name: "mistralai/devstral-small:free",
    id: "Devstral-Small-Free",
  },
  "Mistral-Large": {
    mode: true,
    name: "mistralai/mistral-large",
    id: "Mistral-Large",
  },
  "Mistral-7b-Instruct-Free": {
    mode: true,
    name: "mistralai/mistral-7b-instruct:free",
    id: "Mistral-7b-Instruct-Free",
  },
  "Pixtral-12b": {
    mode: true,
    name: "mistralai/pixtral-12b",
    id: "Pixtral-12b",
  },
  "Mistral-Saba": {
    mode: true,
    name: "mistralai/mistral-saba",
    id: "Mistral-Saba",
  },
  "Mistral-Tiny": {
    mode: true,
    name: "mistralai/mistral-tiny",
    id: "Mistral-Tiny",
  },
  "Mistral-Large-2407": {
    mode: true,
    name: "mistralai/mistral-large-2407",
    id: "Mistral-Large-2407",
  },
  "Mistral-7b-Instruct-v0.3": {
    mode: true,
    name: "mistralai/mistral-7b-instruct-v0.3",
    id: "Mistral-7b-Instruct-v0.3",
  },
  "Mistral-Small-24b-Instruct-2501-Free": {
    mode: true,
    name: "mistralai/mistral-small-24b-instruct-2501:free",
    id: "Mistral-Small-24b-Instruct-2501-Free",
  },
  "Mistral-Small-3.2-24b-Instruct-Free": {
    mode: true,
    name: "mistralai/mistral-small-3.2-24b-instruct:free",
    id: "Mistral-Small-3.2-24b-Instruct-Free",
  },
  "Mistral-Small-24b-Instruct-2501": {
    mode: true,
    name: "mistralai/mistral-small-24b-instruct-2501",
    id: "Mistral-Small-24b-Instruct-2501",
  },
  "Mistral-7b-Instruct": {
    mode: true,
    name: "mistralai/mistral-7b-instruct",
    id: "Mistral-7b-Instruct",
  },
  "Mistral-Small-3.2-24b-Instruct": {
    mode: true,
    name: "mistralai/mistral-small-3.2-24b-instruct",
    id: "Mistral-Small-3.2-24b-Instruct",
  },
  "Mistral-Nemo-Free": {
    mode: true,
    name: "mistralai/mistral-nemo:free",
    id: "Mistral-Nemo-Free",
  },
  "Mistral-7b-Instruct-v0.1": {
    mode: true,
    name: "mistralai/mistral-7b-instruct-v0.1",
    id: "Mistral-7b-Instruct-v0.1",
  },
  "Devstral-Small": {
    mode: true,
    name: "mistralai/devstral-small",
    id: "Devstral-Small",
  },
  "Ministral-3b": {
    mode: true,
    name: "mistralai/ministral-3b",
    id: "Ministral-3b",
  },
  "Pixtral-Large-2411": {
    mode: true,
    name: "mistralai/pixtral-large-2411",
    id: "Pixtral-Large-2411",
  },
  "Mistral-Small-3.1-24b-Instruct-Free": {
    mode: true,
    name: "mistralai/mistral-small-3.1-24b-instruct:free",
    id: "Mistral-Small-3.1-24b-Instruct-Free",
  },
  "Magistral-Medium-2506": {
    mode: true,
    name: "mistralai/magistral-medium-2506",
    id: "Magistral-Medium-2506",
  },
  "Mistral-Medium-3": {
    mode: true,
    name: "mistralai/mistral-medium-3",
    id: "Mistral-Medium-3",
  },
  "Codestral-2501": {
    mode: true,
    name: "mistralai/codestral-2501",
    id: "Codestral-2501",
  },
  "Cognitivecomputations-Dolphin3.0-Mistral-24b-Free": {
    mode: true,
    name: "cognitivecomputations/dolphin3.0-mistral-24b:free",
    id: "Cognitivecomputations-Dolphin3.0-Mistral-24b-Free",
  },
  "Magistral-Small-2506": {
    mode: true,
    name: "mistralai/magistral-small-2506",
    id: "Magistral-Small-2506",
  },
  "Cognitivecomputations-Dolphin3.0-r1-Mistral-24b-Free": {
    mode: true,
    name: "cognitivecomputations/dolphin3.0-r1-mistral-24b:free",
    id: "Cognitivecomputations-Dolphin3.0-r1-Mistral-24b-Free",
  },
  "Mistral-Large-2411": {
    mode: true,
    name: "mistralai/mistral-large-2411",
    id: "Mistral-Large-2411",
  },
  "Mistral-Nemo": {
    mode: true,
    name: "mistralai/mistral-nemo",
    id: "Mistral-Nemo",
  },
  "Mistral-Small-3.1-24b-Instruct": {
    mode: true,
    name: "mistralai/mistral-small-3.1-24b-instruct",
    id: "Mistral-Small-3.1-24b-Instruct",
  },
  Command: {
    mode: true,
    name: "cohere/command",
    id: "Command",
  },
  "Command R": {
    mode: true,
    name: "cohere/command-r",
    id: "Command R",
  },
  "Command R7B 12 2024": {
    mode: true,
    name: "cohere/command-r7b-12-2024",
    id: "Command R7B 12 2024",
  },
  "Command R Plus 04 2024": {
    mode: true,
    name: "cohere/command-r-plus-04-2024",
    id: "Command R Plus 04 2024",
  },
  "Command R Plus": {
    mode: true,
    name: "cohere/command-r-plus",
    id: "Command R Plus",
  },
  "Command A": {
    mode: true,
    name: "cohere/command-a",
    id: "Command A",
  },
  "Command R 08 2024": {
    mode: true,
    name: "cohere/command-r-08-2024",
    id: "Command R 08 2024",
  },
  "Command R Plus 08 2024": {
    mode: true,
    name: "cohere/command-r-plus-08-2024",
    id: "Command R Plus 08 2024",
  },
  "Command R 03 2024": {
    mode: true,
    name: "cohere/command-r-03-2024",
    id: "Command R 03 2024",
  },
  "Gemini-2.5-Flash-Preview-05-20": {
    mode: true,
    name: "google/gemini-2.5-flash-preview-05-20",
    id: "Gemini-2.5-Flash-Preview-05-20",
  },
  "Gemini-2.5-Flash-Preview-05-20:Thinking": {
    mode: true,
    name: "google/gemini-2.5-flash-preview-05-20:thinking",
    id: "Gemini-2.5-Flash-Preview-05-20:Thinking",
  },
  "Gemini-2.5-Pro-Preview-05-06": {
    mode: true,
    name: "google/gemini-2.5-pro-preview-05-06",
    id: "Gemini-2.5-Pro-Preview-05-06",
  },
  "Gemini-2.5-Flash-Lite-Preview-06-17": {
    mode: true,
    name: "google/gemini-2.5-flash-lite-preview-06-17",
    id: "Gemini-2.5-Flash-Lite-Preview-06-17",
  },
  "Gemini-2.5-Flash-Preview": {
    mode: true,
    name: "google/gemini-2.5-flash-preview",
    id: "Gemini-2.5-Flash-Preview",
  },
  "Gemini-Pro-1.5": {
    mode: true,
    name: "google/gemini-pro-1.5",
    id: "Gemini-Pro-1.5",
  },
  "Gemini-2.5-Pro-Exp-03-25": {
    mode: true,
    name: "google/gemini-2.5-pro-exp-03-25",
    id: "Gemini-2.5-Pro-Exp-03-25",
  },
  "Gemini-2.5-Flash": {
    mode: true,
    name: "google/gemini-2.5-flash",
    id: "Gemini-2.5-Flash",
  },
  "Gemini-2.0-Flash-Exp:Free": {
    mode: true,
    name: "google/gemini-2.0-flash-exp:free",
    id: "Gemini-2.0-Flash-Exp:Free",
  },
  "Gemini-Flash-1.5": {
    mode: true,
    name: "google/gemini-flash-1.5",
    id: "Gemini-Flash-1.5",
  },
  "Gemini-2.5-Pro": {
    mode: true,
    name: "google/gemini-2.5-pro",
    id: "Gemini-2.5-Pro",
  },
  "Gemini-2.5-Pro-Preview": {
    mode: true,
    name: "google/gemini-2.5-pro-preview",
    id: "Gemini-2.5-Pro-Preview",
  },
  "Gemini-Flash-1.5-8b": {
    mode: true,
    name: "google/gemini-flash-1.5-8b",
    id: "Gemini-Flash-1.5-8b",
  },
  "Gemini-2.0-Flash-Lite-001": {
    mode: true,
    name: "google/gemini-2.0-flash-lite-001",
    id: "Gemini-2.0-Flash-Lite-001",
  },
  "Gemini-2.0-Flash-001": {
    mode: true,
    name: "google/gemini-2.0-flash-001",
    id: "Gemini-2.0-Flash-001",
  },
  "Gemini-2.5-Flash-Preview:Thinking": {
    mode: true,
    name: "google/gemini-2.5-flash-preview:thinking",
    id: "Gemini-2.5-Flash-Preview:Thinking",
  },
}
const modelList = {
  type: "list",
  data: modelListOrig.map((modelName) => {
    const alias = modelName
    const id = modelName
    return {
      alias,
      id,
      provider: "blackboxai",
    }
  }),
}

export default modelList
export { trendingAgentMode }
