// Defines the structure for a parameter within a tool's function.
export interface ToolParameter {
    type: 'string' | 'number' | 'boolean' | 'object' | 'array';
    description: string;
    required?: boolean;
}

// Defines the structure for a tool that can be called by the model.
export interface Tool {
    name: string;
    description: string;
    parameters: {
        [key: string]: ToolParameter;
    };
}

// Represents the function call generated by the model.
export interface FunctionCall {
    name: string;
    arguments: { [key: string]: any };
}

// Represents a single tool call in the response message.
export interface ToolCall {
    id: string; // A unique ID for the tool call
    type: 'function';
    function: FunctionCall;
}
