export const models = {
  data: [
    {
      alias: "qvq-72b-preview-0310",
      created: 0,
      id: "Blackpink",
      object: "model",
      owned_by: "qwen",
    },
    {
      alias: "qwen2.5-vl-32b-instruct",
      created: 0,
      id: "Jarvis",
      object: "model",
      owned_by: "qwen",
    },
    {
      alias: "qwen2.5-14b-instruct-1m",
      created: 0,
      id: "Black Mamba",
      object: "model",
      owned_by: "qwen",
    },
    {
      alias: "qwen3-30b-a3b",
      created: 0,
      id: "Lisa",
      object: "model",
      owned_by: "qwen",
    },
    {
      alias: "qwen3-32b",
      created: 0,
      id: "Rosseane",
      object: "model",
      owned_by: "qwen",
    },
    {
      alias: "qwen-max-latest",
      created: 0,
      id: "Cichu",
      object: "model",
      owned_by: "qwen",
    },
    {
      alias: "qwq-32b",
      created: 0,
      id: "Chaelisa",
      object: "model",
      owned_by: "qwen",
    },
    {
      alias: "qwen2.5-omni-7b",
      created: 0,
      id: "Blinque",
      object: "model",
      owned_by: "qwen",
    },
    {
      alias: "qwen2.5-coder-32b-instruct",
      created: 0,
      id: "Milea",
      object: "model",
      owned_by: "qwen",
    },
    {
      alias: "qwen2.5-72b-instruct",
      created: 0,
      id: "Dilan",
      object: "model",
      owned_by: "qwen",
    },
    {
      alias: "qwen3-235b-a22b",
      created: 0,
      id: "Jennie",
      object: "model",
      owned_by: "qwen",
    },
  ],
  object: "list",
}
