name: Publish Python Package

on:
  release:
    types: [published]

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.detect.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install toml requests

      - name: Detect Changed Packages
        id: detect
        run: |
          python3 scripts/detect_changed.py
        shell: bash

      - name: Debug matrix output
        run: |
          echo "Matrix: ${{ steps.detect.outputs.matrix }}"

  publish:
    needs: detect
    if: needs.detect.outputs.matrix != '{}' && fromJson(needs.detect.outputs.matrix).include && fromJson(needs.detect.outputs.matrix).include[0]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.detect.outputs.matrix) }}

    defaults:
      run:
        working-directory: ./${{ matrix.package }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry

      - name: Configure PyPI Token
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}

      - name: Build and Publish
        run: |
          poetry build
          poetry publish
